### ISSUE TITLE
pcat报找不到命令？其他模块正常

### ISSUE THREAD

**Issue by BorGMoSS** [yaoxiaonie/asl#1]
Android11&coloros11&OPPOa9_PCAT
面具是金丝雀最新24101，已装模块见图，报错信息见图
![Screenshot_2022-01-30-10-10-45-55_2edfb974afef37529c711c1c2be2596b](https://user-images.githubusercontent.com/63234853/151684048-525407f4-7966-46ff-83d8-631b4c1fd0af.jpg)
![Screenshot_2022-01-29-19-18-27-93_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/63234853/151684052-dc018c77-5b9a-4c96-923b-d799c437eb07.jpg)

**Comment by BorGMoSS** [comment]
好吧
![Stitch_20220130_103926](https://user-images.githubusercontent.com/63234853/151684634-f86843dd-6a87-4c66-9c84-d035da32cdeb.png)

**Comment by Garusuta** [comment]
试试新的修复版本[v2.6-fix](https://github.com/yaoxiaonie/asl/releases/tag/v2.6-fix)
